Gensam
ClinicalGenomicsGBG/sars-cov-2-typing pull request #14
Opened 2021-10-15 11:33 UTC by sima-r

2021-10-20 11:08 UTC, pbiology commented on gensamupload/gensamupload.py
> +                    log.write(writelog("Uploading_info", f'{fastqR1_trgt} dose exist in sftp.'))
typo: does

2021-10-20 11:08 UTC, pbiology commented on gensamupload/gensamupload.py
> +                    log.write(writelog("Uploading_info", f'{fastqR2_trgt} dose exist in sftp.'))
Typo: does

2021-10-20 11:09 UTC, pbiology commented on gensamupload/gensamupload.py
> +                report_data.append('--no-upload')
Why twice?

2021-10-20 11:09 UTC, pbiology commented on gensamupload/gensamupload.py
> +            report_data.append('R1/R2 not found')
Also duplicated row

2021-10-20 11:09 UTC, pbiology commented on gensamupload/gensamupload.py
> +                    log.write(writelog("Uploading_info", f'{fasta_trgt} dose not exist in sftp.'))
typo: does

2021-10-20 11:11 UTC, pbiology commented on nextseq_cronscript.py
> +    print(process1.stdout)
All these print statements should perhaps be removed?

2021-10-20 11:12 UTC, pbiology commented on tools/emailer.py
> +    msg['Cc'] = ["anders.lind.cgg@gu.se", "sima.rahimi@gu.se"]
This whole thing could be moved to config file. Easier to add new e-mails

2021-12-07 13:01 UTC, sima-r commented on gensamupload/gensamupload.py
> +    #header = ['SampleID','criterion','RunID','sequencing_week','fastq1','fastq2','fasta','upload_date','upload_week']
This is not used anywhere, just left it to see how the header looks like in the file. Could be deleted!

2021-12-17 15:25 UTC, pbiology requested changes

2021-12-17 15:25 UTC, pbiology commented on gensamupload/gensamupload.py
> +
Isn't the if/else statements messed up here?
The else statement now is paired with the `if runtype == '00'`, right?

2021-12-17 15:38 UTC, sima-r commented on gensamupload/gensamupload.py
> +
So those samples that are not controls or whatever we put into that list and are not  rerun samples will satisfy the else statement.

2021-12-28 14:01 UTC, pbiology approved these changes

2021-12-28 14:06 UTC, merged