Fix for iontorrent uploads
ClinicalGenomicsGBG/sars-cov-2-typing pull request #46
Opened 2022-09-19 08:44 UTC by CEJ-R

### Priority: 
(High)

### What does this PR aim to solve:
There appears to have been some problems with the uploads of samples from the iontorrent machines. To solve this the code handling this will need to be changed and reviewed. One potential issue are the various versions of pangolin, and how they might affect the parsing.

### Changed in this PR:
- Different handling of csv-separators

2022-09-26 12:59 UTC, JPWerling requested changes

2022-09-26 12:59 UTC, JPWerling commented on microbiology-plugin/covid_seqstore_transfer/covid_seqstore_transfer.py
> +        dialect = csv.Sniffer().sniff(csvfile.readline(), [',',';','\t'])
missing keyword `delimiters=`

2022-09-26 12:59 UTC, JPWerling commented on microbiology-plugin/covid_seqstore_transfer/covid_seqstore_transfer.py
> +        dialect = csv.Sniffer().sniff(csvfile.readline(), [',',';','\t'])
`Sniff` does not work for tabs
https://stackoverflow.com/questions/51074335/delimiter-with-tab-in-text-file

2022-09-28 13:33 UTC, CEJ-R commented
@JPWerling Then I'm not sure what to say, as it seems to work fine when run on the iontorrent (just this part of the script) `/home/ionadmin/misc_scripts/emilio_covid_script/broken_covid_seqstore_transfer.py`. There I have this function, fed with some xls', and it seems to produce a reasonable dict when written like the PR currently has it.

2023-02-20 10:15 UTC, CEJ-R commented
This should now work as intended and is ready for merging before I deal with the wrapper-side.

2023-02-23 14:43 UTC, JPWerling requested changes
Everything looks to function apart from a missing `selection_criteria` definition unless I'm blind

2023-02-23 14:43 UTC, JPWerling commented on microbiology_s5/runner.py
> +                    sftp_connection.put(f_path, os.path.basename(filename))
Redundant `basename`

2023-02-23 14:43 UTC, JPWerling commented on microbiology_s5/src/reformat.py
> +                clean_meta = sample_metadata.rstrip()  # Clean newline from string
could fix this in the js parser

2023-02-23 14:43 UTC, JPWerling commented on microbiology_s5/src/reformat.py
> +                    selection_criteria_text = selection_criteria[selection_criteria_index]
I don't see `selection_criteria` defined

2023-02-23 14:43 UTC, JPWerling commented on microbiology_s5/src/reformat.py
> +                print(','.join([sample_name, selection_criteria_text, '']), file=out)
Could use a comment on what the last `''` is for

2023-02-27 09:48 UTC, CEJ-R commented on microbiology-plugin/covid_seqstore_transfer/covid_seqstore_transfer.py
> +                print("barcode: {} did not have metadata:".format(barcode)) # Note that the top row of metadata is assumed to be header
Yes... this was before I knew that there would (probably) never be headers. Changed!

2023-02-27 09:49 UTC, CEJ-R commented on microbiology_s5/config.py
> +ERROR_EMAIL = ['cgg-micro@gu.se']
I think this is probably better as separate list. KMIK usually want different people to get different sendouts with the covid-stuff. I do intend on adding a bunch more emails here once this goes live.

2023-02-27 09:49 UTC, CEJ-R commented on microbiology_s5/runner.py
> +                    sftp_connection.put(f_path, os.path.basename(filename))
Good catch!

2023-02-27 09:50 UTC, CEJ-R commented on microbiology_s5/src/reformat.py
> +                    selection_criteria_text = selection_criteria[selection_criteria_index]
It reads from an import:
https://github.com/ClinicalGenomicsGBG/sars-cov-2-typing/blob/232d958feb4ac00d31d2decd22b62c8e1726d8f2/microbiology_s5/src/reformat.py#L9

2023-02-27 09:50 UTC, CEJ-R commented on microbiology_s5/src/reformat.py
> +                print(','.join([sample_name, selection_criteria_text, '']), file=out)
Yes... and this needs patching later as well. More covid fun for the future!

2023-02-27 09:51 UTC, CEJ-R commented on microbiology_s5/src/reformat.py
> +                clean_meta = sample_metadata.rstrip()  # Clean newline from string
I think I'll leave it as is here (python), since I know how this is supposed to work.

2023-03-13 07:44 UTC, JPWerling approved these changes

2023-03-28 05:48 UTC, merged